### ISSUE TITLE
SEO?

### ISSUE THREAD

**Issue by raphaelokon** [briangonzalez/codrops-medium-style-page-transitions#3]
Thank you for this awesome insight. Do you have any SEO related suggestions?

**Comment by briangonzalez** [comment]
I didn't take SEO into consideration too much due to the scope of the tutorial.

Here are a couple of worthy reads, though:

[How To: Allow Google to Crawl your AJAX Content](http://moz.com/blog/how-to-allow-google-to-crawl-ajax-content) 
[The LINK Tag, REL attribute and SEO](http://www.pitstopmedia.com/sem/link-tag-rel-attribute-seo)
